# Generated by Django 6.1.1 on 2026-09-19 00:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bean_amount', models.IntegerField()),
                ('bean_grind', models.CharField(max_length=10)),
                ('bean_rost', models.CharField(max_length=10)),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('weather', models.CharField(max_length=10)),
                ('atmospheric_pressure', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
