# Generated by Django 6.1.1 on 2026-09-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_coffee_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
